package com.epam.catalog.controller.command;

public enum CommandName {
	SEARCH_BOOK_LESS_THAN_PRICE,
	SEARCH_BOOK_BY_AUTHOR,
	SEARCH_BOOK_BY_ID,
	GET_ALL_BOOKS,
	ADD_BOOK,
	DELETE_BOOK_BY_ID,
	SEARCH_DISK_BY_NAME,
	SEARCH_DISK_LESS_THAN_PRICE,
	ADD_DISK,
	SEARCH_FILM_BY_NAME,
	SEARCH_FILM_BIGGER_THAN_RATING,
	ADD_FILM,
	WRONG_REQUEST

}
